# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ForWorkEditor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        self.add_functions()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 768)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 0))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.treeWidget = QtWidgets.QTreeWidget(self.centralwidget)
        self.treeWidget.setGeometry(QtCore.QRect(11, 11, 221, 721))
        self.treeWidget.setObjectName("treeWidget")
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_0 = QtWidgets.QTreeWidgetItem(self.treeWidget)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        item_1 = QtWidgets.QTreeWidgetItem(item_0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 26))
        self.menubar.setObjectName("menubar")
        self.menu_1 = QtWidgets.QMenu(self.menubar)
        self.menu_1.setObjectName("menu_1")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        self.menu_3 = QtWidgets.QMenu(self.menubar)
        self.menu_3.setObjectName("menu_3")
        MainWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menu_1.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())
        self.menubar.addAction(self.menu_3.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Заполнение и редактирование"))
        self.treeWidget.headerItem().setText(0, _translate("MainWindow", "Меню"))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("MainWindow", "Наряд"))
        self.treeWidget.topLevelItem(1).setText(0, _translate("MainWindow", "Отчёт"))
        self.treeWidget.topLevelItem(2).setText(0, _translate("MainWindow", "Продажи"))
        self.treeWidget.topLevelItem(3).setText(0, _translate("MainWindow", "Сводка"))
        self.treeWidget.topLevelItem(4).setText(0, _translate("MainWindow", "Журнал осмотров"))
        self.treeWidget.topLevelItem(5).setText(0, _translate("MainWindow", "Подрядчики"))
        self.treeWidget.topLevelItem(5).child(0).setText(0, _translate("MainWindow", "Дальавтотранс"))
        self.treeWidget.topLevelItem(5).child(1).setText(0, _translate("MainWindow", "Техники и технологии"))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.menu_1.setTitle(_translate("MainWindow", "Диспетчер"))
        self.menu_2.setTitle(_translate("MainWindow", "Кассир"))
        self.menu_3.setTitle(_translate("MainWindow", "Бухгалтер"))

    def add_functions(self):
        pass


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
