# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\NewBus.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(640, 535)
        Dialog.setModal(True)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(550, 460, 81, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonBox.setFont(font)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Close)
        self.buttonBox.setObjectName("buttonBox")
        self.new_bus_num_edit = QtWidgets.QLineEdit(Dialog)
        self.new_bus_num_edit.setGeometry(QtCore.QRect(160, 20, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_bus_num_edit.setFont(font)
        self.new_bus_num_edit.setObjectName("new_bus_num_edit")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 70, 91, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.new_bus_gosnomer_edit = QtWidgets.QLineEdit(Dialog)
        self.new_bus_gosnomer_edit.setGeometry(QtCore.QRect(160, 70, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_bus_gosnomer_edit.setFont(font)
        self.new_bus_gosnomer_edit.setObjectName("new_bus_gosnomer_edit")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(10, 120, 141, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.new_bus_odometr_edit = QtWidgets.QLineEdit(Dialog)
        self.new_bus_odometr_edit.setGeometry(QtCore.QRect(160, 120, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_bus_odometr_edit.setFont(font)
        self.new_bus_odometr_edit.setObjectName("new_bus_odometr_edit")
        self.bus_list = QtWidgets.QListWidget(Dialog)
        self.bus_list.setGeometry(QtCore.QRect(10, 240, 431, 231))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bus_list.setFont(font)
        self.bus_list.setObjectName("bus_list")
        self.bus_delete_button = QtWidgets.QPushButton(Dialog)
        self.bus_delete_button.setGeometry(QtCore.QRect(470, 330, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bus_delete_button.setFont(font)
        self.bus_delete_button.setObjectName("bus_delete_button")
        self.bus_save_button = QtWidgets.QPushButton(Dialog)
        self.bus_save_button.setGeometry(QtCore.QRect(470, 150, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bus_save_button.setFont(font)
        self.bus_save_button.setObjectName("bus_save_button")
        self.bus_edit_button = QtWidgets.QPushButton(Dialog)
        self.bus_edit_button.setGeometry(QtCore.QRect(470, 240, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.bus_edit_button.setFont(font)
        self.bus_edit_button.setObjectName("bus_edit_button")
        self.label_5 = QtWidgets.QLabel(Dialog)
        self.label_5.setGeometry(QtCore.QRect(10, 20, 131, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(Dialog)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 71, 22))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.new_bus_model_edit = QtWidgets.QLineEdit(Dialog)
        self.new_bus_model_edit.setGeometry(QtCore.QRect(160, 180, 171, 22))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.new_bus_model_edit.setFont(font)
        self.new_bus_model_edit.setText("")
        self.new_bus_model_edit.setObjectName("new_bus_model_edit")

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Автобусы"))
        self.label_2.setText(_translate("Dialog", "Гос. номер"))
        self.label_3.setText(_translate("Dialog", "Одометр"))
        self.bus_delete_button.setText(_translate("Dialog", "Удалить автобус\n"
" из списка"))
        self.bus_save_button.setText(_translate("Dialog", "Добавить автобус\n"
" в список"))
        self.bus_edit_button.setText(_translate("Dialog", "Отредактировать \n"
"автобус"))
        self.label_5.setText(_translate("Dialog", "Бортовой номер"))
        self.label_4.setText(_translate("Dialog", "Модель"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
