# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui\OrderWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1382, 742)
        font = QtGui.QFont()
        font.setPointSize(14)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(20, 240, 1331, 431))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1382, 31))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_driver = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_driver.setFont(font)
        self.action_driver.setShortcutContext(QtCore.Qt.WidgetWithChildrenShortcut)
        self.action_driver.setObjectName("action_driver")
        self.action_cond = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_cond.setFont(font)
        self.action_cond.setObjectName("action_cond")
        self.action_bus = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_bus.setFont(font)
        self.action_bus.setObjectName("action_bus")
        self.action_route = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_route.setFont(font)
        self.action_route.setObjectName("action_route")
        self.action_disp = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_disp.setFont(font)
        self.action_disp.setObjectName("action_disp")
        self.action_mech = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.action_mech.setFont(font)
        self.action_mech.setObjectName("action_mech")
        self.menu.addAction(self.action_driver)
        self.menu.addAction(self.action_cond)
        self.menu.addSeparator()
        self.menu.addAction(self.action_bus)
        self.menu.addAction(self.action_route)
        self.menu.addSeparator()
        self.menu.addAction(self.action_disp)
        self.menu.addAction(self.action_mech)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menu.setTitle(_translate("MainWindow", "Администрирование"))
        self.action_driver.setText(_translate("MainWindow", "Водитель"))
        self.action_cond.setText(_translate("MainWindow", "Кондуктор"))
        self.action_bus.setText(_translate("MainWindow", "Автобусы"))
        self.action_route.setText(_translate("MainWindow", "Маршруты"))
        self.action_disp.setText(_translate("MainWindow", "Диспетчеры"))
        self.action_mech.setText(_translate("MainWindow", "Механики"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
